#!/bin/sh

docker build . -t ampfct

bmpfont() {
        docker run --rm -v $PWD:/ampfct ampfct convert $1.bmp $1.png
        docker run --rm -v $PWD:/ampfct ampfct ./ampfct.py $@
}

bmpfont term_font 8 11 16 16 0 0 b &
bmpfont unifont 16 16 256 256 32 64 w
